package main

import "fmt"

func convert(dna string) (rna string) {
	st := []byte(dna)
	for _, base := range st {
		if string(base) == "T" {
			rna += "U"
		} else {
			rna += string(base)
		}
	}
	return
}

func main() {
	dna := "TTCGGTCGGATAGGAGCCGCTACACATACGTTATTCATTGTTACCGAGTGGTCAGCTTACAATACTACCTTCCTCCCCCAAAAGTTTGATACACGGAAGGGTTCCGCAAATAGAGACTTGGCACTTGAGAATCTAGACCTAGGCCTAGTTGTTTGTTATTAATGTTATCTCCTAAGCTTGCTTTATCCATTCTCCTTAATTATTACCCTTAAGAAACCCACCGCGACTAACATTCGCTGAGTTGGTTAACGAGCGGGGAGTACAATGTACAGGGCCCAGGTCAGTCCATGGAATATTTTTACATTATTTGTAGCTCCGGCAGGACACCCTTCCCCGGTCGAGCATATCTTGAACTAAGAGATATAGGCACCCAACTCAGGGGCGCTAATTAAACTAGCCCACTAAACCGAGGCATATCCTTAGCGAATTTAGAATTCATAACCGAATTGCTGGTCTTCGACCGATGTCAGTCCAACCTCAACTTGTTTCTTAGGCAATGCATCAAACCTGCTAGCTTAGTGTCCACTGACCACTTTCCGCCGCCAACGGGGGGCGAGGACGAGGCTCCCTAATACGTTCTTACTGAAGCCACTTAGTCCTCTAATAATAGGCGTACGAGCCAAGGACTTCCCCGAGAAACAGAAGCATTTCGTAGAACTTAAAGGTGATCCCCTAGGCTGTGTATGCATTGCCCATTTAAATTAGCTGTATTACCATGAGCACCAGCACGGTCACTATTCTGGTGGATACAAGATAACTTGCCACTTCCGGCACGGGTTTCAACAAGGATTACGTTTATGGACTCCTTTAAAATTTAGGCACGTTAGGATCTTCCTGAGAATCCCAGGATCCCATGGCGTGGCCGACTCAAGAAATCAATTTGAACCCACGGCTACTTGTAACCCCTCATCGCAAGATAAGATTCAGAGTGTGCTGCCCAAC"
	rna := convert(dna)
	fmt.Println(rna)
}
